
# Buildare ed eseguire senza errori il programma

#dopodichè buildare con le flag -fprofile-arcs -ftest-coverage

# gcov main.cpp

# lcov -c --directory . --output-file main_coverage.info

# genhtml main_coverage.info --output-directory out
